
// This file has been generated by the GUI designer. Do not modify.
namespace Prototip
{
#if MONO
	public partial class GtkFormMain
	{
		private global::Gtk.HBox hbox4;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Label label1;

		private global::Gtk.Button btnNovaIgra;

		private global::Gtk.Button btnPostavke;

		private global::Gtk.Button btnUcitaj;

		private global::Gtk.Button btnUgasi;

		private global::Gtk.Fixed fixed4;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Fixed fixed7;

		private global::Gtk.Label label4;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Prototip.GtkFormMain
			this.Name = "Prototip.GtkFormMain";
			this.Title = global::Mono.Unix.Catalog.GetString ("GtkFormMain");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Prototip.GtkFormMain.Gtk.Container+ContainerChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.WidthRequest = 160;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox4.Add (this.fixed1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.fixed1]));
			w1.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Zvjezdojedac");
			this.vbox6.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.btnNovaIgra = new global::Gtk.Button ();
			this.btnNovaIgra.CanFocus = true;
			this.btnNovaIgra.Name = "btnNovaIgra";
			this.btnNovaIgra.UseUnderline = true;
			this.btnNovaIgra.Label = global::Mono.Unix.Catalog.GetString ("New Game");
			this.vbox6.Add (this.btnNovaIgra);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.btnNovaIgra]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.btnPostavke = new global::Gtk.Button ();
			this.btnPostavke.CanFocus = true;
			this.btnPostavke.Name = "btnPostavke";
			this.btnPostavke.UseUnderline = true;
			this.btnPostavke.Label = global::Mono.Unix.Catalog.GetString ("Load Game");
			this.vbox6.Add (this.btnPostavke);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.btnPostavke]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.btnUcitaj = new global::Gtk.Button ();
			this.btnUcitaj.CanFocus = true;
			this.btnUcitaj.Name = "btnUcitaj";
			this.btnUcitaj.UseUnderline = true;
			this.btnUcitaj.Label = global::Mono.Unix.Catalog.GetString ("Settings");
			this.vbox6.Add (this.btnUcitaj);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.btnUcitaj]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.btnUgasi = new global::Gtk.Button ();
			this.btnUgasi.CanFocus = true;
			this.btnUgasi.Name = "btnUgasi";
			this.btnUgasi.UseUnderline = true;
			this.btnUgasi.Label = global::Mono.Unix.Catalog.GetString ("Exit");
			this.vbox6.Add (this.btnUgasi);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.btnUgasi]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed ();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			this.vbox6.Add (this.fixed4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.fixed4]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 5;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox4.Add (this.vbox6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox6]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.fixed7 = new global::Gtk.Fixed ();
			this.fixed7.HeightRequest = 336;
			this.fixed7.Name = "fixed7";
			this.fixed7.HasWindow = false;
			this.vbox2.Add (this.fixed7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.fixed7]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.WidthRequest = 160;
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Ivan Kravarščan 2011.");
			this.vbox2.Add (this.label4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label4]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.hbox4.Add (this.vbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox2]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.Add (this.hbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 409;
			this.DefaultHeight = 360;
			this.Show ();
		}
	}
#endif
}
